/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.CtrlPQR;
import modelo.pqr;
import modelo.sqlPQR;
import modelo.usuarios;

import com.mysql.jdbc.Connection;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import modelo.Conexion;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Administrador
 */
public class home extends javax.swing.JFrame {

    usuarios mod;
    
    /**
     * Creates new form home
     */
    public home() {
        initComponents();
    }
    
    public home(usuarios mod){
        initComponents();
        setLocationRelativeTo(null);
        this.mod = mod;
        
        lblNombre.setText(mod.getUsuario());
        lblRol.setText(mod.getNombre_tipo());
        
        if(mod.getId_tipo() == 1){
            
        }else if (mod.getId_tipo() == 2){
            menuReportes.setVisible(false);
            menuUsuario.setVisible(false);
            //lblUsuario.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombre = new javax.swing.JLabel();
        lblRol = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuUsuario = new javax.swing.JMenu();
        subCrearUsuario = new javax.swing.JMenuItem();
        menuReportes = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        MenuConsulta = new javax.swing.JMenu();
        subMenuCqueja = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblRol.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        menuUsuario.setText("Usuarios");

        subCrearUsuario.setText("Configurar Usuario");
        subCrearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subCrearUsuarioActionPerformed(evt);
            }
        });
        menuUsuario.add(subCrearUsuario);

        jMenuBar1.add(menuUsuario);

        menuReportes.setText("Reportes");

        jMenuItem4.setText("Generar Reporte");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        menuReportes.add(jMenuItem4);

        jMenuBar1.add(menuReportes);

        MenuConsulta.setText("Consultas");

        subMenuCqueja.setText("consultar queja");
        subMenuCqueja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuCquejaActionPerformed(evt);
            }
        });
        MenuConsulta.add(subMenuCqueja);

        jMenuBar1.add(MenuConsulta);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblRol, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                    .addComponent(lblNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(244, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(lblRol, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(138, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        try {
            Conexion con = new Conexion();
            Connection conn = (Connection) con.getConexion();
            
            JasperReport reporte = null;
            String path = "src\\Reportes\\reportePQR.jasper";
            
            //Map parametro = new HashMap();
            //parametro.put("id_estado", 36);
            
            reporte = (JasperReport) JRLoader.loadObjectFromFile(path);
            
            JasperPrint jprint = JasperFillManager.fillReport(reporte, null, conn);
            
            JasperViewer view = new JasperViewer(jprint, false);
            
            view.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            
            view.setVisible(true);
            
        } catch (JRException ex) {
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void subCrearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subCrearUsuarioActionPerformed
        // TODO add your handling code here:
         pqr mod = new pqr();
        sqlPQR modC= new sqlPQR();
        registroPQR frm = new registroPQR();
        ConsultasQuejas frmCQ = new ConsultasQuejas();
        CtrlPQR ctrl = new CtrlPQR(mod, modC, frm, frmCQ);
        ctrl.iniciar();
        frm.setVisible(true);
    }//GEN-LAST:event_subCrearUsuarioActionPerformed

    private void subMenuCquejaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuCquejaActionPerformed
        // TODO add your handling code here:
        pqr mod = new pqr();
        sqlPQR modC= new sqlPQR();
        registroPQR frm = new registroPQR();
        ConsultasQuejas frmCQ = new ConsultasQuejas();
        CtrlPQR ctrl = new CtrlPQR(mod, modC, frm, frmCQ);
        ctrl.iniciar();
        frmCQ.setVisible(true);
    }//GEN-LAST:event_subMenuCquejaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuConsulta;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblRol;
    private javax.swing.JMenu menuReportes;
    private javax.swing.JMenu menuUsuario;
    private javax.swing.JMenuItem subCrearUsuario;
    private javax.swing.JMenuItem subMenuCqueja;
    // End of variables declaration//GEN-END:variables
}
